name: CI/CD Pipeline

# Trigger Ã  chaque push sur n'importe quelle branche
on:
  push:

jobs:
  hello-job:
    runs-on: ubuntu-latest   # Le type de machine virtuelle

    steps:
      - name: Say Hello
        run: echo "Hello CI/CD"
